# GitHub Packages Configuration
# This file helps GitHub identify published packages

packages:
  - name: "@fly4react/observer"
    description: "一个基于 Intersection Observer API 的现代 React 工具库"
    repository: "https://github.com/yyyyyyyyyunf/react-toolkit"
    registry: "https://registry.npmjs.org/"
    latest_version: "1.26.0"
    
  - name: "@fly4react/memo"
    description: "一个高级的 React 记忆化组件工具"
    repository: "https://github.com/yyyyyyyyyunf/react-toolkit"
    registry: "https://registry.npmjs.org/"
    latest_version: "1.6.2"
    
  - name: "@fly4react/image"
    description: "React 图像优化和懒加载工具库"
    repository: "https://github.com/yyyyyyyyyunf/react-toolkit"
    registry: "https://registry.npmjs.org/"
    latest_version: "1.12.2"
    
  - name: "@fly4react/feature-detector"
    description: "一个纯 JavaScript 浏览器特性检测库"
    repository: "https://github.com/yyyyyyyyyunf/react-toolkit"
    registry: "https://registry.npmjs.org/"
    latest_version: "1.1.1"
